[phases.setup]
nixPkgs = ["php", "php.packages.composer", "nodejs", "mysql", "git"]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "composer require laravel/sanctum",
  "php artisan vendor:publish --provider=\"Laravel\\Sanctum\\SanctumServiceProvider\"",
  "npm install",
  "npm run build",
  "php artisan key:generate",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
